sudo: false
language: python
python:
  - '2.7'
  - '3.5'
cache: pip
before_install:
  - pip install --upgrade pip
install:
  # FIXME: Test with released versions once they're available
  - pip install git+https://github.com/praekelt/molo.git@py3
  - pip install git+https://github.com/praekelt/django-google-analytics.git@py3

  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - molo scaffold testapp
  - mkdir -p testapp/testapp/templates/registration/
  - cp molo/profiles/test_templates/login.html testapp/testapp/templates/registration/
  - pip install -e testapp
  - py.test --cov=molo
  - flake8 molo
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: "kw+xYAhY/4aR6vVvFzhXetaXXB1fn04zlxWZrDbPjYFUmhzziO3bE++bP+f5K8ozFHpPMVrRGdie7DNroxyAH+YEAz8TUxt6ZWPk0UlBvOHhFCihCG3wvASK7bmqKDYNM6eZtJ4sEHCrVRM1v5t9FWT+jOZ3iYTHqH7jQJ1Yoo8XCJ/SvUxonc7kejtanjZFg1+q/mgQz2pvHnw+GG3yrS0KZp5LeQ1ioZQS+Jm84cXV4st7DxQLvvvYtW3BmiezLXGJATylwqnM+oMEpfFYngfOApXyvbPpU01Ajb2mb1r1kX7QA3i4Z8FRNefQo7F5Z3r/gHdlL3AnnlgIxWScxElt9xb6Z4vPmCIWgdvldC7hsmnB9/dSktG1pvMeTXUiKrJjxLoWfrcKiXR5pba1XbwbHCUftcjdzTAGPo84BVc2hZ4pbxWQKo6JZF6gycJNBFyCwRikmLhJWiHMQCKnDlaa7JpaDdK3xGXLRN59/vfuwqy2Q339ErMMwVgxKes2m6WmFd6QantHNIONX/hXqV725FHKBvLUsRVeG1bM/1Fd6TgL9xtYipkZxqiVUJ+OBs1u8mKs4d9chAFJCoVffnkqC/GciIU4UvJh4vt4bslTwfPwil4ww82iGUZnGwxEUEJmLFtBRtGZDmyDVL+O990G/L+Z+1KPZeUf4NGdM1w="
  on:
    tags: true
    all_branches: true
